dist: trusty
sudo: required

language: node_js

node_js:
  - "10.9.0"

cache:
  directories:
    - "node_modules"

addons:
  chrome: stable

before_script:
- yarn global add @angular/cli

script: ng t JDNConvertibleCalendarDateAdapter --watch=false --browsers=ChromeHeadless
