dist: trusty
sudo: required

language: node_js

node_js:
  - "10.9.0"

cache:
  directories:
    - "node_modules"

addons:
  chrome: stable

script:
  - npm run ng t --project jdnconvertiblecalendardateadapter --watch=false --browsers=ChromeHeadless
  - npm run ng b --project jdnconvertiblecalendardateadapter
